import type {Metadata} from "next";
import {Raleway} from "next/font/google";
import '@/app/styles/global.scss'
import {ContentWidthProvider} from "@/app/providers/ContentWidthProvider";
import {FontSizeProvider} from "@/app/providers/FontSizeProvider";
import {LineHeightProvider} from "@/app/providers/LineHeightProvider";
import {ThemeProvider} from "@/app/providers/ThemeProvider";
import {ThemeToggle} from "@/features/theme-toggle";

const Font = Raleway({
  weight: ['400', '500', '600', '700'],
  variable: "--font-main",
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="ru">
    <body className={`${Font.variable}`}>
    <ThemeProvider>
      <FontSizeProvider>
        <LineHeightProvider>
          <ContentWidthProvider>
            {children}
            <ThemeToggle />
          </ContentWidthProvider>
        </LineHeightProvider>
      </FontSizeProvider>
    </ThemeProvider>
    </body>
    </html>
  );
}
