import type {Metadata} from "next";
import {Jost} from "next/font/google";
import "../_app/styles/global.scss";
import {ThemeProvider} from "@/_app/providers/ThemeProvider";
import {ThemeToggle} from "@/widgets/shared/ui/ThemeToggle";

const PoppinsFont = Jost({
  weight: ['400', '500', '600', '700'],
  variable: "--font-poppins",
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="ru">
    <body className={`${PoppinsFont.variable}`}>
    <ThemeProvider>
      {children}
      <ThemeToggle />
    </ThemeProvider>
    </body>
    </html>
  );
}
